DATA:
  DATASET:
    TYPE: VoxAudio
    ROOT_DIR: /root/autodl-tmp/datasets/VoxCeleb1
    FRAME_LEN: 32
    HOP_LEN: 5
    NAME: audio2pose
    NUM_CLASSES: 46
  TRAIN_BATCH_SIZE: 64
  EVAL_BATCH_SIZE: 64
  NUM_WORKERS: 4


MODEL:
  TYPE: Audio2Pose
  CHECKPOINT: 'checkpoints/audio2pose_00140.pth'
  AUDIOENCODER:
    LEAKY_RELU: True
    NORM: 'IN'
  DISCRIMINATOR:
    LEAKY_RELU: False
    INPUT_CHANNELS: 6
  CVAE:
    AUDIO_EMB_IN_SIZE: 512
    AUDIO_EMB_OUT_SIZE: 6
    SEQ_LEN: 32
    LATENT_SIZE: 64
    ENCODER_LAYER_SIZES: [192, 128]
    DECODER_LAYER_SIZES: [128, 192]
    

TRAIN:
  MAX_EPOCH: 150
  G_LR: 1.0e-4
  D_LR: 1.0e-4
  LR_DECAY_EPOCH: 45
  WEIGHT_DECAY: 0
  LOSS_WEIGHT:
    W_REG: 1
    W_GAN: 0.7
    W_KL: 1

TAG:
  NAME: cvae_UNET_useAudio_usewav2lipAudioEncoder


